query product($slug: String) {
    product(slug: $slug) {
        items {
            images {
                imageId
                imageUrl
                imageLabel
            }
        }
    }
}